Asian:
    [BayanNur,Aw2,Aw3,kiang,Kia2,hemionus]

African:
    [Sp-5,Eg-1,Ch-by1,Ke-14,Ky-5,Ir-5,somalicus]

Anatolian:
    [cdh008]

All:
    [BayanNur,Aw2,Aw3,kiang,Kia2,hemionus,Sp-5,Eg-1,Ch-by1,Ke-14,Ky-5,Ir-5,somalicus,cdh008]
